services:
  backend:
    build: ./backend
    container_name: mob-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: mob-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
